# Generated by Django 4.0.3 on 2022-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_number', models.CharField(max_length=256)),
                ('category_product', models.CharField(max_length=256)),
                ('review_content', models.TextField()),
                ('first_status', models.BooleanField()),
                ('second_status', models.BooleanField()),
                ('dummy_status', models.BooleanField()),
                ('first_labeled_id', models.CharField(max_length=256)),
                ('second_labeled_id', models.CharField(max_length=256)),
            ],
        ),
    ]
