# Generated by Django 4.0.3 on 2022-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dummy_status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='first_labeled_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='first_status',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_number',
        ),
        migrations.RemoveField(
            model_name='review',
            name='second_labeled_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='second_status',
        ),
    ]
